FROM python:3.10-slim

WORKDIR /app

# 1. Upgrade pip
RUN pip install --upgrade pip

# 2. Install requirements (keeping it light)
RUN pip install flwr numpy tensorflow-cpu flask requests pandas scikit-learn

# 3. Copy your specific application code
COPY attacker/ /app
COPY shared/ /app/shared
COPY model/ /app/model
COPY data/ /app/data

CMD ["python", "attacker.py"]