FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    libgomp1 \
    git \
    cmake \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# upgrade pip first
RUN pip install --upgrade pip

# install regular python packages from PyPI
RUN pip install \
    tensorflow-cpu \
    flwr \
    numpy \
    pandas \
    scikit-learn \
    pynacl \
    cryptography \
    COPY model/ /app/model

COPY vehicle/ /app
COPY shared/ /app/shared
COPY model/ /app/model

CMD ["python", "main.py"]