FROM python:3.10-slim

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install \
    flwr \
    tensorflow-cpu\
    numpy

COPY server/ /app
COPY shared/ /app/shared
COPY model/ /app/model
COPY data/ /app/data

CMD ["python", "server.py"]